<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="55b1d169-957a-4731-927a-59e50fdc8c14" name="dwilloug@PHINEAS 2012-11-03 22:34:29" runUser="USERS\dwilloug" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="33500a2c-091e-4f9b-a348-a6603a00d679">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="dwilloug_PHINEAS 2012-11-03 22_34_29">
      <DeploymentItem filename="D:\Users\dwilloug\PS7\PS7\bin\Debug\PS7.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2012-11-03T22:34:29.6646334-06:00" queuing="2012-11-03T22:34:29.7516334-06:00" start="2012-11-03T22:34:29.7646334-06:00" finish="2012-11-03T22:34:36.3524334-06:00" />
  <ResultSummary outcome="Error">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
    <RunInfos>
      <RunInfo computerName="PHINEAS" outcome="Error" timestamp="2012-11-03T22:34:36.2276334-06:00">
        <Text>One of the background threads threw exception: 
System.Net.Sockets.SocketException (0x80004005): A blocking operation was interrupted by a call to WSACancelBlockingCall
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.Socket.Receive(Byte[] buffer)
   at CustomNetworking.StringSocket.receivingLoop() in D:\Users\dwilloug\PS7\PS7\StringSocket.cs:line 222
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="Test3" storage="d:\users\dwilloug\ps7\stringsockettester\bin\debug\stringsockettester.dll" id="cf7e051b-6af1-98eb-0b17-1e537981674d">
      <Execution id="6f331efc-fd5e-4b8c-b34f-e6e3cf3495fb" />
      <TestMethod codeBase="D:\Users\dwilloug\PS7\StringSocketTester\bin\Debug\StringSocketTester.dll" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="StringSocketTester.StringSocketTest, StringSocketTester" name="Test3" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="cf7e051b-6af1-98eb-0b17-1e537981674d" executionId="6f331efc-fd5e-4b8c-b34f-e6e3cf3495fb" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="6f331efc-fd5e-4b8c-b34f-e6e3cf3495fb" testId="cf7e051b-6af1-98eb-0b17-1e537981674d" testName="Test3" computerName="PHINEAS" duration="00:00:06.1701846" startTime="2012-11-03T22:34:29.7716334-06:00" endTime="2012-11-03T22:34:36.2432334-06:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="6f331efc-fd5e-4b8c-b34f-e6e3cf3495fb">
      <Output>
        <ErrorInfo>
          <Message>Assert.IsTrue failed. Didn't receive in timely fashion 48</Message>
          <StackTrace>   at StringSocketTester.StringSocketTest.Test3Class.run(Int32 port) in D:\Users\dwilloug\PS7\StringSocketTester\StringSocketTest.cs:line 436
   at StringSocketTester.StringSocketTest.Test3() in D:\Users\dwilloug\PS7\StringSocketTester\StringSocketTest.cs:line 382
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>